### PR TITLE
Initial ansible commits

### PR DESCRIPTION
**Pull request by P0intMaN**
Addressing issue(s):
- #2

### CODE REVIEW

**Review by CYBERDEVILZ — CHANGES_REQUESTED** [review]
Hey @P0intMaN 
Looks like the files are just initial commits. Kindly add more details to it.

**Comment by P0intMaN** [comment]
Yeah adding them in the next set of PRs. You may close this now

**Comment by P0intMaN** [comment]
you may merge this

**Comment by P0intMaN** [comment]
i can put separate PRs. Let this go into the code.

**Pull request merged**
